network.host: 0.0.0.0
network.publish_host: 52.203.178.151
cluster.name: mycluster
node.name: node_master
node.master: true
node.data: true
http.port : 9200
tcp.port : 9300
discovery.zen.ping.multicast.enabled: false

marvel.agent.exporters:

  id1:
    type: http
    host: ["52.203.178.151:9200"]